name: Cancel Practice
description: Cancel a scheduled practice
title: "[Practice] Cancel: "
labels: ["practice-change"]
body:
  - type: dropdown
    id: team
    attributes:
      label: Team
      options:
        - MDB Knights 11U Gold
        - MDB Knights 14U Blue
        - MDB Knights 11U Blue
        - MDB Knights 13U Gold
        - MDB Knights 13U Blue
        - MDB Knights 10U Gold
        - Braintree Bandits 11U Mercado
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date of practice to cancel
      description: "Format: YYYY-MM-DD"
      placeholder: "2026-04-15"
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: Reason (optional)
      placeholder: "Rain / field unavailable / etc."
    validations:
      required: false
